//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing_v2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://MagniAPI/Invoicing/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Invoicing_v2.SpecialAuthentication))]
    public partial class Authentication : object
    {
        
        private string EmailField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialAuthentication", Namespace="http://MagniAPI/Invoicing/")]
    public partial class SpecialAuthentication : Invoicing_v2.Authentication
    {
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewPartnerInformation", Namespace="http://MagniAPI/Invoicing/")]
    public partial class NewPartnerInformation : object
    {
        
        private string UserNameField;
        
        private string UserEmailField;
        
        private string UserPhoneField;
        
        private string CompanyTaxIdField;
        
        private string CompanyLegalNameField;
        
        private string CompanyAddressField;
        
        private string CompanyCityField;
        
        private string CompanyPostCodeField;
        
        private string CompanyCountryField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserEmail
        {
            get
            {
                return this.UserEmailField;
            }
            set
            {
                this.UserEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserPhone
        {
            get
            {
                return this.UserPhoneField;
            }
            set
            {
                this.UserPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyTaxId
        {
            get
            {
                return this.CompanyTaxIdField;
            }
            set
            {
                this.CompanyTaxIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyLegalName
        {
            get
            {
                return this.CompanyLegalNameField;
            }
            set
            {
                this.CompanyLegalNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CompanyAddress
        {
            get
            {
                return this.CompanyAddressField;
            }
            set
            {
                this.CompanyAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CompanyCity
        {
            get
            {
                return this.CompanyCityField;
            }
            set
            {
                this.CompanyCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CompanyPostCode
        {
            get
            {
                return this.CompanyPostCodeField;
            }
            set
            {
                this.CompanyPostCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CompanyCountry
        {
            get
            {
                return this.CompanyCountryField;
            }
            set
            {
                this.CompanyCountryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://MagniAPI/Invoicing/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Invoicing_v2.ResponseOfListOfAPIAccessTokenBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Invoicing_v2.ResponseOfDocumentCreateOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Invoicing_v2.ResponseOfDocumentGetOut))]
    public partial class Response : object
    {
        
        private string RequestIdField;
        
        private Invoicing_v2.ResponseType TypeField;
        
        private Invoicing_v2.ErrorType ErrorValueField;
        
        private string ErrorHumanReadableField;
        
        private System.Collections.Generic.List<Invoicing_v2.ValidationError> ValidationErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Invoicing_v2.ResponseType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Invoicing_v2.ErrorType ErrorValue
        {
            get
            {
                return this.ErrorValueField;
            }
            set
            {
                this.ErrorValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorHumanReadable
        {
            get
            {
                return this.ErrorHumanReadableField;
            }
            set
            {
                this.ErrorHumanReadableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<Invoicing_v2.ValidationError> ValidationErrors
        {
            get
            {
                return this.ValidationErrorsField;
            }
            set
            {
                this.ValidationErrorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorType", Namespace="http://MagniAPI/Invoicing/")]
    public partial class ErrorType : Invoicing_v2.MagniEnum
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfListOfAPIAccessTokenBase", Namespace="http://MagniAPI/Invoicing/")]
    public partial class ResponseOfListOfAPIAccessTokenBase : Invoicing_v2.Response
    {
        
        private System.Collections.Generic.List<Invoicing_v2.APIAccessTokenBase> ObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<Invoicing_v2.APIAccessTokenBase> Object
        {
            get
            {
                return this.ObjectField;
            }
            set
            {
                this.ObjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfDocumentCreateOut", Namespace="http://MagniAPI/Invoicing/")]
    public partial class ResponseOfDocumentCreateOut : Invoicing_v2.Response
    {
        
        private Invoicing_v2.DocumentCreateOut ObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Invoicing_v2.DocumentCreateOut Object
        {
            get
            {
                return this.ObjectField;
            }
            set
            {
                this.ObjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfDocumentGetOut", Namespace="http://MagniAPI/Invoicing/")]
    public partial class ResponseOfDocumentGetOut : Invoicing_v2.Response
    {
        
        private Invoicing_v2.DocumentGetOut ObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Invoicing_v2.DocumentGetOut Object
        {
            get
            {
                return this.ObjectField;
            }
            set
            {
                this.ObjectField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseType", Namespace="http://MagniAPI/Invoicing/")]
    public enum ResponseType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationError", Namespace="http://MagniAPI/Invoicing/")]
    public partial class ValidationError : object
    {
        
        private string FieldNameField;
        
        private int ElementNumberField;
        
        private string TypeField;
        
        private string FieldField;
        
        private string DetailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ElementNumber
        {
            get
            {
                return this.ElementNumberField;
            }
            set
            {
                this.ElementNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Detail
        {
            get
            {
                return this.DetailField;
            }
            set
            {
                this.DetailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MagniEnum", Namespace="http://MagniAPI/Invoicing/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Invoicing_v2.ErrorType))]
    public partial class MagniEnum : object
    {
        
        private int ValueField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIAccessTokenBase", Namespace="http://MagniAPI/Invoicing/")]
    public partial class APIAccessTokenBase : object
    {
        
        private string AccessTokenField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentCreateOut", Namespace="http://MagniAPI/Invoicing/")]
    public partial class DocumentCreateOut : object
    {
        
        private int DocumentIdField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentGetOut", Namespace="http://MagniAPI/Invoicing/")]
    public partial class DocumentGetOut : object
    {
        
        private string DocumentNumberField;
        
        private int DocumentIdField;
        
        private string DownloadUrlField;
        
        private string PaymentStatusField;
        
        private string ErrorMessageField;
        
        private string TotalAmountField;
        
        private string UnpaidAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentNumber
        {
            get
            {
                return this.DocumentNumberField;
            }
            set
            {
                this.DocumentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DownloadUrl
        {
            get
            {
                return this.DownloadUrlField;
            }
            set
            {
                this.DownloadUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PaymentStatus
        {
            get
            {
                return this.PaymentStatusField;
            }
            set
            {
                this.PaymentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string UnpaidAmount
        {
            get
            {
                return this.UnpaidAmountField;
            }
            set
            {
                this.UnpaidAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://MagniAPI/Invoicing/")]
    public partial class Client : object
    {
        
        private string NIFField;
        
        private string NameField;
        
        private string AddressField;
        
        private string CityField;
        
        private string PostCodeField;
        
        private string CountryCodeField;
        
        private string PhoneNumberField;
        
        private string CountryNameField;
        
        private string LegalNameField;
        
        private string EmailField;
        
        private string IBANField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NIF
        {
            get
            {
                return this.NIFField;
            }
            set
            {
                this.NIFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PostCode
        {
            get
            {
                return this.PostCodeField;
            }
            set
            {
                this.PostCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CountryName
        {
            get
            {
                return this.CountryNameField;
            }
            set
            {
                this.CountryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string LegalName
        {
            get
            {
                return this.LegalNameField;
            }
            set
            {
                this.LegalNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentIn", Namespace="http://MagniAPI/Invoicing/")]
    public partial class DocumentIn : object
    {
        
        private string DateField;
        
        private string DueDateField;
        
        private string DescriptionField;
        
        private string TypeField;
        
        private string SerieField;
        
        private int IdField;
        
        private string TaxExemptionReasonCodeField;
        
        private string CurrencyField;
        
        private System.Nullable<decimal> EuroRateField;
        
        private string ExternalIdField;
        
        private System.Collections.Generic.List<Invoicing_v2.APIInvoicingProduct> LinesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Serie
        {
            get
            {
                return this.SerieField;
            }
            set
            {
                this.SerieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TaxExemptionReasonCode
        {
            get
            {
                return this.TaxExemptionReasonCodeField;
            }
            set
            {
                this.TaxExemptionReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> EuroRate
        {
            get
            {
                return this.EuroRateField;
            }
            set
            {
                this.EuroRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public System.Collections.Generic.List<Invoicing_v2.APIInvoicingProduct> Lines
        {
            get
            {
                return this.LinesField;
            }
            set
            {
                this.LinesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIInvoicingProduct", Namespace="http://MagniAPI/Invoicing/")]
    public partial class APIInvoicingProduct : object
    {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private decimal UnitPriceField;
        
        private decimal QuantityField;
        
        private string UnitField;
        
        private string TypeField;
        
        private decimal TaxValueField;
        
        private decimal ProductDiscountField;
        
        private string CostCenterField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal TaxValue
        {
            get
            {
                return this.TaxValueField;
            }
            set
            {
                this.TaxValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal ProductDiscount
        {
            get
            {
                return this.ProductDiscountField;
            }
            set
            {
                this.ProductDiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CostCenter
        {
            get
            {
                return this.CostCenterField;
            }
            set
            {
                this.CostCenterField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MagniAPI/Invoicing/", ConfigurationName="Invoicing_v2.InvoicingSoap")]
    public interface InvoicingSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MagniAPI/Invoicing/AddPartner", ReplyAction="*")]
        System.Threading.Tasks.Task<Invoicing_v2.AddPartnerResponse> AddPartnerAsync(Invoicing_v2.AddPartnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MagniAPI/Invoicing/GetPartnerTokens", ReplyAction="*")]
        System.Threading.Tasks.Task<Invoicing_v2.GetPartnerAccessTokensResponse> GetPartnerAccessTokensAsync(Invoicing_v2.GetPartnerAccessTokensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MagniAPI/Invoicing/DocumentCreate", ReplyAction="*")]
        System.Threading.Tasks.Task<Invoicing_v2.DocumentCreateResponse> DocumentCreateAsync(Invoicing_v2.DocumentCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MagniAPI/Invoicing/DocumentGet", ReplyAction="*")]
        System.Threading.Tasks.Task<Invoicing_v2.DocumentGetResponse> DocumentGetAsync(Invoicing_v2.DocumentGetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPartnerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPartner", Namespace="http://MagniAPI/Invoicing/", Order=0)]
        public Invoicing_v2.AddPartnerRequestBody Body;
        
        public AddPartnerRequest()
        {
        }
        
        public AddPartnerRequest(Invoicing_v2.AddPartnerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MagniAPI/Invoicing/")]
    public partial class AddPartnerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Invoicing_v2.Authentication Authentication;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Invoicing_v2.NewPartnerInformation PartnerInformation;
        
        public AddPartnerRequestBody()
        {
        }
        
        public AddPartnerRequestBody(Invoicing_v2.Authentication Authentication, Invoicing_v2.NewPartnerInformation PartnerInformation)
        {
            this.Authentication = Authentication;
            this.PartnerInformation = PartnerInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPartnerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPartnerResponse", Namespace="http://MagniAPI/Invoicing/", Order=0)]
        public Invoicing_v2.AddPartnerResponseBody Body;
        
        public AddPartnerResponse()
        {
        }
        
        public AddPartnerResponse(Invoicing_v2.AddPartnerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MagniAPI/Invoicing/")]
    public partial class AddPartnerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Invoicing_v2.Response ResponseAddPartner;
        
        public AddPartnerResponseBody()
        {
        }
        
        public AddPartnerResponseBody(Invoicing_v2.Response ResponseAddPartner)
        {
            this.ResponseAddPartner = ResponseAddPartner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerAccessTokensRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerAccessTokens", Namespace="http://MagniAPI/Invoicing/", Order=0)]
        public Invoicing_v2.GetPartnerAccessTokensRequestBody Body;
        
        public GetPartnerAccessTokensRequest()
        {
        }
        
        public GetPartnerAccessTokensRequest(Invoicing_v2.GetPartnerAccessTokensRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MagniAPI/Invoicing/")]
    public partial class GetPartnerAccessTokensRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Invoicing_v2.SpecialAuthentication SpecialAuthentication;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PartnerTaxId;
        
        public GetPartnerAccessTokensRequestBody()
        {
        }
        
        public GetPartnerAccessTokensRequestBody(Invoicing_v2.SpecialAuthentication SpecialAuthentication, string PartnerTaxId)
        {
            this.SpecialAuthentication = SpecialAuthentication;
            this.PartnerTaxId = PartnerTaxId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPartnerAccessTokensResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPartnerAccessTokensResponse", Namespace="http://MagniAPI/Invoicing/", Order=0)]
        public Invoicing_v2.GetPartnerAccessTokensResponseBody Body;
        
        public GetPartnerAccessTokensResponse()
        {
        }
        
        public GetPartnerAccessTokensResponse(Invoicing_v2.GetPartnerAccessTokensResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MagniAPI/Invoicing/")]
    public partial class GetPartnerAccessTokensResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Invoicing_v2.ResponseOfListOfAPIAccessTokenBase ResponseGetPartnerAccessTokens;
        
        public GetPartnerAccessTokensResponseBody()
        {
        }
        
        public GetPartnerAccessTokensResponseBody(Invoicing_v2.ResponseOfListOfAPIAccessTokenBase ResponseGetPartnerAccessTokens)
        {
            this.ResponseGetPartnerAccessTokens = ResponseGetPartnerAccessTokens;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentCreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocumentCreate", Namespace="http://MagniAPI/Invoicing/", Order=0)]
        public Invoicing_v2.DocumentCreateRequestBody Body;
        
        public DocumentCreateRequest()
        {
        }
        
        public DocumentCreateRequest(Invoicing_v2.DocumentCreateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MagniAPI/Invoicing/")]
    public partial class DocumentCreateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Invoicing_v2.Authentication Authentication;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Invoicing_v2.Client Client;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Invoicing_v2.DocumentIn Document;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsToClose;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SendTo;
        
        public DocumentCreateRequestBody()
        {
        }
        
        public DocumentCreateRequestBody(Invoicing_v2.Authentication Authentication, Invoicing_v2.Client Client, Invoicing_v2.DocumentIn Document, bool IsToClose, string SendTo)
        {
            this.Authentication = Authentication;
            this.Client = Client;
            this.Document = Document;
            this.IsToClose = IsToClose;
            this.SendTo = SendTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocumentCreateResponse", Namespace="http://MagniAPI/Invoicing/", Order=0)]
        public Invoicing_v2.DocumentCreateResponseBody Body;
        
        public DocumentCreateResponse()
        {
        }
        
        public DocumentCreateResponse(Invoicing_v2.DocumentCreateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MagniAPI/Invoicing/")]
    public partial class DocumentCreateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Invoicing_v2.ResponseOfDocumentCreateOut Response;
        
        public DocumentCreateResponseBody()
        {
        }
        
        public DocumentCreateResponseBody(Invoicing_v2.ResponseOfDocumentCreateOut Response)
        {
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentGetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocumentGet", Namespace="http://MagniAPI/Invoicing/", Order=0)]
        public Invoicing_v2.DocumentGetRequestBody Body;
        
        public DocumentGetRequest()
        {
        }
        
        public DocumentGetRequest(Invoicing_v2.DocumentGetRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MagniAPI/Invoicing/")]
    public partial class DocumentGetRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Invoicing_v2.Authentication Authentication;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DocumentId;
        
        public DocumentGetRequestBody()
        {
        }
        
        public DocumentGetRequestBody(Invoicing_v2.Authentication Authentication, int DocumentId)
        {
            this.Authentication = Authentication;
            this.DocumentId = DocumentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentGetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DocumentGetResponse", Namespace="http://MagniAPI/Invoicing/", Order=0)]
        public Invoicing_v2.DocumentGetResponseBody Body;
        
        public DocumentGetResponse()
        {
        }
        
        public DocumentGetResponse(Invoicing_v2.DocumentGetResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MagniAPI/Invoicing/")]
    public partial class DocumentGetResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Invoicing_v2.ResponseOfDocumentGetOut Response;
        
        public DocumentGetResponseBody()
        {
        }
        
        public DocumentGetResponseBody(Invoicing_v2.ResponseOfDocumentGetOut Response)
        {
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface InvoicingSoapChannel : Invoicing_v2.InvoicingSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class InvoicingSoapClient : System.ServiceModel.ClientBase<Invoicing_v2.InvoicingSoap>, Invoicing_v2.InvoicingSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InvoicingSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(InvoicingSoapClient.GetBindingForEndpoint(endpointConfiguration), InvoicingSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvoicingSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InvoicingSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvoicingSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InvoicingSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvoicingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Invoicing_v2.AddPartnerResponse> Invoicing_v2.InvoicingSoap.AddPartnerAsync(Invoicing_v2.AddPartnerRequest request)
        {
            return base.Channel.AddPartnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Invoicing_v2.AddPartnerResponse> AddPartnerAsync(Invoicing_v2.Authentication Authentication, Invoicing_v2.NewPartnerInformation PartnerInformation)
        {
            Invoicing_v2.AddPartnerRequest inValue = new Invoicing_v2.AddPartnerRequest();
            inValue.Body = new Invoicing_v2.AddPartnerRequestBody();
            inValue.Body.Authentication = Authentication;
            inValue.Body.PartnerInformation = PartnerInformation;
            return ((Invoicing_v2.InvoicingSoap)(this)).AddPartnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Invoicing_v2.GetPartnerAccessTokensResponse> Invoicing_v2.InvoicingSoap.GetPartnerAccessTokensAsync(Invoicing_v2.GetPartnerAccessTokensRequest request)
        {
            return base.Channel.GetPartnerAccessTokensAsync(request);
        }
        
        public System.Threading.Tasks.Task<Invoicing_v2.GetPartnerAccessTokensResponse> GetPartnerAccessTokensAsync(Invoicing_v2.SpecialAuthentication SpecialAuthentication, string PartnerTaxId)
        {
            Invoicing_v2.GetPartnerAccessTokensRequest inValue = new Invoicing_v2.GetPartnerAccessTokensRequest();
            inValue.Body = new Invoicing_v2.GetPartnerAccessTokensRequestBody();
            inValue.Body.SpecialAuthentication = SpecialAuthentication;
            inValue.Body.PartnerTaxId = PartnerTaxId;
            return ((Invoicing_v2.InvoicingSoap)(this)).GetPartnerAccessTokensAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Invoicing_v2.DocumentCreateResponse> Invoicing_v2.InvoicingSoap.DocumentCreateAsync(Invoicing_v2.DocumentCreateRequest request)
        {
            return base.Channel.DocumentCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Invoicing_v2.DocumentCreateResponse> DocumentCreateAsync(Invoicing_v2.Authentication Authentication, Invoicing_v2.Client Client, Invoicing_v2.DocumentIn Document, bool IsToClose, string SendTo)
        {
            Invoicing_v2.DocumentCreateRequest inValue = new Invoicing_v2.DocumentCreateRequest();
            inValue.Body = new Invoicing_v2.DocumentCreateRequestBody();
            inValue.Body.Authentication = Authentication;
            inValue.Body.Client = Client;
            inValue.Body.Document = Document;
            inValue.Body.IsToClose = IsToClose;
            inValue.Body.SendTo = SendTo;
            return ((Invoicing_v2.InvoicingSoap)(this)).DocumentCreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Invoicing_v2.DocumentGetResponse> Invoicing_v2.InvoicingSoap.DocumentGetAsync(Invoicing_v2.DocumentGetRequest request)
        {
            return base.Channel.DocumentGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Invoicing_v2.DocumentGetResponse> DocumentGetAsync(Invoicing_v2.Authentication Authentication, int DocumentId)
        {
            Invoicing_v2.DocumentGetRequest inValue = new Invoicing_v2.DocumentGetRequest();
            inValue.Body = new Invoicing_v2.DocumentGetRequestBody();
            inValue.Body.Authentication = Authentication;
            inValue.Body.DocumentId = DocumentId;
            return ((Invoicing_v2.InvoicingSoap)(this)).DocumentGetAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InvoicingSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.InvoicingSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InvoicingSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://bo.magnifinance.com/MagniAPI/Invoicing.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.InvoicingSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://bo.magnifinance.com/MagniAPI/Invoicing.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            InvoicingSoap,
            
            InvoicingSoap12,
        }
    }
}
